server:
  port: 8888

logging:
  path: logs
  file: userManager.log

spring:
  application:
    name: userManager
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/course
    username: admin
    password: 123456a

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*